CC = gcc
CFLAGS = -g -Wall 
LDFLAGS = 
LDLIBS = 

mdb-lookup-server-nc-2:  

.PHONY: clean
clean:
	rm -f *.o mdb-lookup-server-nc-2 mdb-lookup-server-nc-1

.PHONY: all
all: clean mdb-lookup-server-nc-2
